# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'str1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 90, 251, 451))
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(16, 6, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(66, 1, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(66, 10, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(270, 90, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 120, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.status = QtWidgets.QTextEdit(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(270, 130, 431, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.status.setFont(font)
        self.status.setStyleSheet("border: 0; background-color: #f0f0f0;")
        self.status.setReadOnly(True)
        self.status.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.status.setObjectName("status")
        self.info = QtWidgets.QTextEdit(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(270, 160, 111, 81))
        self.info.setStyleSheet("border: 0; background-color: #f0f0f0;")
        self.info.setReadOnly(True)
        self.info.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.info.setObjectName("info")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 95, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.info_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.info_2.setGeometry(QtCore.QRect(390, 160, 391, 81))
        self.info_2.setStyleSheet("border: 0; background-color: #f0f0f0;")
        self.info_2.setReadOnly(True)
        self.info_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.info_2.setObjectName("info_2")
        self.post = QtWidgets.QTextEdit(self.centralwidget)
        self.post.setGeometry(QtCore.QRect(270, 250, 391, 71))
        self.post.setObjectName("post")
        self.publish = QtWidgets.QPushButton(self.centralwidget)
        self.publish.setGeometry(QtCore.QRect(670, 250, 91, 71))
        self.publish.setObjectName("publish")
        self.status_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.status_2.setGeometry(QtCore.QRect(710, 130, 21, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.status_2.setFont(font)
        self.status_2.setStyleSheet("border: 0; background-color: #f0f0f0;")
        self.status_2.setReadOnly(True)
        self.status_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.status_2.setObjectName("status_2")
        self.id = QtWidgets.QTextEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(740, 130, 41, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.id.setFont(font)
        self.id.setStyleSheet("border: 0; background-color: #f0f0f0;")
        self.id.setReadOnly(True)
        self.id.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.id.setObjectName("id")
        self.posts = QtWidgets.QTableWidget(self.centralwidget)
        self.posts.setGeometry(QtCore.QRect(270, 330, 511, 221))
        self.posts.setStyleSheet("border:0; background-color: #f0f0f0;")
        self.posts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.posts.setObjectName("posts")
        self.posts.setColumnCount(0)
        self.posts.setRowCount(0)
        self.posts.horizontalHeader().setVisible(False)
        self.posts.horizontalHeader().setDefaultSectionSize(480)
        self.posts.horizontalHeader().setMinimumSectionSize(480)
        self.posts.verticalHeader().setVisible(True)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(710, 30, 75, 23))
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Ч"))
        self.label_3.setText(_translate("MainWindow", "то"))
        self.label_4.setText(_translate("MainWindow", "с"))
        self.label_5.setText(_translate("MainWindow", "лучилось?"))
        self.name.setText(_translate("MainWindow", "Владислав Луценко"))
        self.status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">статус</p></body></html>"))
        self.info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">День рождения: </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Город:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Пол:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Редактировать"))
        self.info_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">23.02.2005</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Санкт-Петербург</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">мужской</p></body></html>"))
        self.publish.setText(_translate("MainWindow", "Опубликовать"))
        self.status_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:normal;\">id:</span></p></body></html>"))
        self.id.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">0001</span></p></body></html>"))
        self.back.setText(_translate("MainWindow", "Назад"))
